dist: trusty

language:
  - cpp
  
compiler:
  - gcc
  
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - libgtest-dev
    - libsfml-dev

install:
  - sudo pip install cpp-coveralls
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

script:
  - make
  - ./Crash2D_Test

after_success:
- coveralls --root library/
